### ISSUE TITLE
能否将题目等信息隐藏

### ISSUE THREAD

**Issue by pisceswb** [choyy/small-window#1]
请问小窗中能否将内容里的题目、面包屑等信息隐藏，只显示聚焦的块？因为标签中已经有题目了

**Comment by pisceswb** [comment]
再次建议，请问能否将下图中圈出的部分隐藏，只保留正文内容，谢谢！@choyy

![image](https://github.com/choyy/small-window/assets/104658457/6d347be4-88a4-4f67-9215-2b808d535d9d)

**Comment by choyy** [comment]
没必要啊，文档内容多了往下划拉不就看不见了

**Comment by pisceswb** [comment]
开小窗是为了获得一个简洁环境，个人感觉越简洁越好。

**Comment by choyy** [comment]
想要更简洁可以聚焦
