### ISSUE TITLE
不兼容docker

### ISSUE THREAD

**Issue by leommjj** [choyy/small-window#2]

**Comment by choyy** [comment]
docker是用浏览器打开的吧，思源并不能打开一个浏览器窗口
不过你可以试试这个插件：[Zuoqiu-Yingyi/siyuan-plugin-webview: [READ ONLY] Subtree split of the siyuan-packages-monorepo (see https://github.com/Zuoqiu-Yingyi/siyuan-packages-monorepo)](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-webview)
